### ISSUE TITLE
npm windows bash error, path substitution error, cannot find module C:\c\

### ISSUE THREAD

**Issue by AuthorProxy** [git-for-windows/git#2916]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64
```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19041.630]
```
### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
git-for-windows\bin\bash

### ERROR:

any npm command throw errors:

```
npm i
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'C:\c\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'C:\c\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}```

**Comment by dscho** [comment]
Please work on providing a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/minimal-reproducible-example). It will dramatically increase your chances to receive helpful assistance.

**Comment by AuthorProxy** [comment]
mmm, what? here is an overload sample, not just minimal

**Comment by dscho** [comment]
Here's why this is not a verifiable example:

```
$ npm i
npm WARN git-for-windows.github.io@0.1.1 No license field.

audited 207 packages in 1.189s
found 67 vulnerabilities (21 low, 17 moderate, 28 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

As you can see, it does not fail at all over here. FWIW here is a bit more information from my side (do take inspiration from this verbosity):

```
$ which npm
/c/Program Files/nodejs/npm
```

and

```
$ npm version
{
  'git-for-windows.github.io': '0.1.1',
  npm: '6.14.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.0',
  http_parser: '2.9.3',
  icu: '65.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.2',
  openssl: '1.1.1e',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '7.8.279.23-node.34',
  zlib: '1.2.11'
}
```
