### ISSUE TITLE
 fatal: unable to access 'https://github.com/mozilla/nunjucks.git/': error setting certificate verify locations:

### ISSUE THREAD

**Issue by snowdream** [git-for-windows/git#363]
when i install gitbook in the git bash console,error happened
```
$ npm install gitbook -g
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  git+https://github.com/mozilla/nunjucks.git#b4351ec0752b102ebd02c5e2cbc2898a6e0e4839 resetting remote C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/mozilla/nunjucks.git C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a: Cloning into bare repository 'C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a'...
npm ERR! git clone --template=C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/mozilla/nunjucks.git C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a: fatal: unable to access 'https://github.com/mozilla/nunjucks.git/': error setting certificate verify locations:
npm ERR! git clone --template=C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/mozilla/nunjucks.git C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a:   CAfile: D:\bin\Git\mingw64/bin/curl-ca-bundle.crt
npm ERR! git clone --template=C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/mozilla/nunjucks.git C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a:   CApath: none
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\bin\\nodejs\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gitbook" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/mozilla/nunjucks.git C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a
npm ERR! Cloning into bare repository 'C:\Users\hui.yang\AppData\Roaming\npm-cache\_git-remotes\https-github-com-mozilla-nunjucks-git-2907d78a'...
npm ERR! fatal: unable to access 'https://github.com/mozilla/nunjucks.git/': error setting certificate verify locations:
npm ERR!   CAfile: D:\bin\Git\mingw64/bin/curl-ca-bundle.crt
npm ERR!   CApath: none
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\company\development-md\npm-debug.log

```

**Comment by snowdream** [comment]
Solution:
http://hydra.geht.net/tino/howto/linux/fixes/curl/

@dscho

**Comment by dscho** [comment]
@snowdream wow. You must think I am a mind reader. And I must be a dimwit because I no understand! I need follow link puzzle together solution? That you want?

:stuck_out_tongue_winking_eye:

**Comment by dscho** [comment]
@snowdream okay, here is a more helpful feedback: since you want me to understand you, please follow [our guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) to come up with a description of the problem I can understand, and with an easy-to-follow, minimal, complete and verifiable example that helps me to reproduce quickly.

**Comment by dscho** [comment]
> CAfile: D:\bin\Git\mingw64/bin/curl-ca-bundle.crt

It might just be a bad configuration. Our installer does not do that, but it seems that somebody (you?) configured Git to look in the wrong path. Our installer would have configured the path to be `.../mingw64/ssl/certs/ca-bundle.crt`.

**Comment by snowdream** [comment]
@dscho i will check it later.

**Comment by dscho** [comment]
@snowdream did you?

**Comment by snowdream** [comment]
```
$ curl -v https://raw.githubusercontent.com/snowdream/gitm/master/examples/repository/repo.gitm
* timeout on name lookup is not supported
*   Trying 103.245.222.133...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to raw.githubusercontent.com (103.245.222.133) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: D:/bin/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0* Unknown SSL protocol error in connection to raw.githubusercontent.com:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to raw.githubusercontent.com:443

```

**Comment by snowdream** [comment]
MayBe my operation is wrong. close it.
