### ISSUE TITLE
ssh.exe: console device allocation failure - too many consoles in use, max consoles is 32

### ISSUE THREAD

**Issue by yunwu-jnpr** [git-for-windows/git#4127]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
C:\>git --version --build-options
git version 2.38.0.windows.1
cpu: x86_64
built from commit: 0355083fbe5582f6d3f819afc130ed2f2375e0bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\>cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.2130]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
   No `install-options.txt`. I downloaded the portable version of git for windows.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
   Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
   Both CMD and PowerShell can reproduce the problem.
   bash won't reproduce the problem.

 - What commands did you run to trigger this issue? If you can provide a
   I have been using git provided `ssh.exe` as `remote.SSH.path` in my vscode for a long time.
   And I always open several vscode windows and open multiple folders on the SSH server.
   And almost every 2 weeks, my vscode will run into `console device allocation failure - too many consoles in use, max consoles is 32`. The following is the full log:

```
[15:09:23.426] Log Level: 2
[15:09:23.433] remote-ssh@0.92.0
[15:09:23.433] win32 x64
[15:09:23.451] SSH Resolver called for "ssh-remote+hp", attempt 1
[15:09:23.452] "remote.SSH.useLocalServer": false
[15:09:23.452] "remote.SSH.showLoginTerminal": false
[15:09:23.453] "remote.SSH.remotePlatform": {"nas":"linux","nas-private":"linux","hp":"linux","hp-private":"linux"}
[15:09:23.453] "remote.SSH.path": D:\tool\git\usr\bin\ssh.exe
[15:09:23.453] "remote.SSH.configFile": undefined
[15:09:23.453] "remote.SSH.useFlock": true
[15:09:23.453] "remote.SSH.lockfilesInTmp": false
[15:09:23.453] "remote.SSH.localServerDownload": auto
[15:09:23.453] "remote.SSH.remoteServerListenOnSocket": false
[15:09:23.453] "remote.SSH.showLoginTerminal": false
[15:09:23.454] "remote.SSH.defaultExtensions": []
[15:09:23.454] "remote.SSH.loglevel": 2
[15:09:23.454] "remote.SSH.enableDynamicForwarding": true
[15:09:23.454] "remote.SSH.enableRemoteCommand": false
[15:09:23.454] "remote.SSH.serverPickPortsFromRange": {}
[15:09:23.454] "remote.SSH.serverInstallPath": {}
[15:09:23.458] SSH Resolver called for host: hp
[15:09:23.458] Setting up SSH remote "hp"
[15:09:23.463] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:09:23.467] Install and start server if needed
[15:09:23.470] Checking ssh with "D:\tool\git\usr\bin\ssh.exe -V"
[15:09:24.568] > OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022

[15:09:24.578] Running script with connection command: "D:\tool\git\usr\bin\ssh.exe" -T -D 61275 hp bash
[15:09:24.582] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:26.717] >       0 [main] ssh 5143 D:\tool\git\usr\bin\ssh.exe: *** fatal error - console d
> evice allocation failure - too many consoles in use, max consoles is 32
> ]0;C:\WINDOWS\System32\cmd.exe    628 [main] ssh 5143 cygwin_exception::open_stackdumpfile: Dumping stack trac
> e to ssh.exe.stackdump
[15:09:26.718] Got some output, clearing connection timeout
[15:09:26.818] > The process tried to write to a nonexistent pipe.
[15:09:28.084] "install" terminal command done
[15:09:28.084] Install terminal quit with output: e to ssh.exe.stackdump
[15:09:28.084] Received install output: e to ssh.exe.stackdump
[15:09:28.084] Failed to parse remote port from server output
[15:09:28.086] Resolver error: Error: 
	at g.Create (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[15:09:28.093] ------




[15:09:28.193] ------




[15:09:28.193] SSH Resolver called for "ssh-remote+hp", attempt 2, (Reconnection)
[15:09:28.196] SSH Resolver called for host: hp
[15:09:28.196] Setting up SSH remote "hp"
[15:09:28.198] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:09:28.200] Install and start server if needed
[15:09:28.204] Running script with connection command: "D:\tool\git\usr\bin\ssh.exe" -T -D 61282 hp bash
[15:09:28.208] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:28.563] >       0 [main] ssh 5144 D:\tool\git\usr\bin\ssh.exe: *** fatal error - console d
> evice allocation failure - too many consoles in use, max consoles is 32
> ]0;C:\WINDOWS\System32\cmd.exe
[15:09:28.563] Got some output, clearing connection timeout
[15:09:28.588] >     460 [main] ssh 5144 cygwin_exception::open_stackdumpfile: Dumping stack trac
> e to ssh.exe.stackdump
[15:09:28.656] > The process tried to write to a nonexistent pipe.
[15:09:29.941] "install" terminal command done
[15:09:29.941] Install terminal quit with output: e to ssh.exe.stackdump
[15:09:29.941] Received install output: e to ssh.exe.stackdump
[15:09:29.941] Failed to parse remote port from server output
[15:09:29.942] Resolver error: Error: 
	at g.Create (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[15:09:29.944] ------




[15:09:29.951] ------




[15:09:29.951] SSH Resolver called for "ssh-remote+hp", attempt 3, (Reconnection)
[15:09:29.952] SSH Resolver called for host: hp
[15:09:29.953] Setting up SSH remote "hp"
[15:09:29.954] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:09:29.956] Install and start server if needed
[15:09:29.959] Running script with connection command: "D:\tool\git\usr\bin\ssh.exe" -T -D 61284 hp bash
[15:09:29.962] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:31.370] >       0 [main] ssh 5145 D:\tool\git\usr\bin\ssh.exe: *** fatal error - console d
> evice allocation failure - too many consoles in use, max consoles is 32
> ]0;C:\WINDOWS\System32\cmd.exe
[15:09:31.371] Got some output, clearing connection timeout
[15:09:31.396] >     495 [main] ssh 5145 cygwin_exception::open_stackdumpfile: Dumping stack trac
> e to ssh.exe.stackdump
[15:09:31.454] > The process tried to write to a nonexistent pipe.
[15:09:32.728] "install" terminal command done
[15:09:32.728] Install terminal quit with output: e to ssh.exe.stackdump
[15:09:32.729] Received install output: e to ssh.exe.stackdump
[15:09:32.729] Failed to parse remote port from server output
[15:09:32.730] Resolver error: Error: 
	at g.Create (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[15:09:32.733] ------




[15:09:32.739] ------




[15:09:32.739] SSH Resolver called for "ssh-remote+hp", attempt 4, (Reconnection)
[15:09:32.741] SSH Resolver called for host: hp
[15:09:32.741] Setting up SSH remote "hp"
[15:09:32.744] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:09:32.749] Install and start server if needed
[15:09:32.754] Running script with connection command: "D:\tool\git\usr\bin\ssh.exe" -T -D 61290 hp bash
[15:09:32.758] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:34.164] >       0 [main] ssh 5146 D:\tool\git\usr\bin\ssh.exe: *** fatal error - console d
> evice allocation failure - too many consoles in use, max consoles is 32
> ]0;C:\WINDOWS\System32\cmd.exe
[15:09:34.164] Got some output, clearing connection timeout
[15:09:34.185] >     470 [main] ssh 5146 cygwin_exception::open_stackdumpfile: Dumping stack trac
> e to ssh.exe.stackdump
[15:09:34.265] > The process tried to write to a nonexistent pipe.
[15:09:35.549] "install" terminal command done
[15:09:35.549] Install terminal quit with output: e to ssh.exe.stackdump
[15:09:35.549] Received install output: e to ssh.exe.stackdump
[15:09:35.550] Failed to parse remote port from server output
[15:09:35.550] Resolver error: Error: 
	at g.Create (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[15:09:35.553] ------




[15:09:35.586] ------




[15:09:35.586] SSH Resolver called for "ssh-remote+hp", attempt 5, (Reconnection)
[15:09:35.588] SSH Resolver called for host: hp
[15:09:35.588] Setting up SSH remote "hp"
[15:09:35.591] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:09:35.593] Install and start server if needed
[15:09:35.597] Running script with connection command: "D:\tool\git\usr\bin\ssh.exe" -T -D 61296 hp bash
[15:09:35.602] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:35.970] >       0 [main] ssh 5147 D:\tool\git\usr\bin\ssh.exe: *** fatal error - console d
> evice allocation failure - too many consoles in use, max consoles is 32
> ]0;C:\WINDOWS\System32\cmd.exe
[15:09:35.970] Got some output, clearing connection timeout
[15:09:35.985] >     572 [main] ssh 5147 cygwin_exception::open_stackdumpfile: Dumping stack trac
> e to ssh.exe.stackdump
[15:09:36.058] > The process tried to write to a nonexistent pipe.
[15:09:37.348] "install" terminal command done
[15:09:37.348] Install terminal quit with output: e to ssh.exe.stackdump
[15:09:37.348] Received install output: e to ssh.exe.stackdump
[15:09:37.349] Failed to parse remote port from server output
[15:09:37.349] Resolver error: Error: 
	at g.Create (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\yunw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[15:09:37.352] ------
```

   When this problem happens:
   Using `ssh.exe` in CMD or PowerShell window shows same error:
```
C:\Users\yunw>ssh hp-private
      0 [main] ssh 5198 D:\tool\Git\usr\bin\ssh.exe: *** fatal error - console device allocation failure - too many consoles in use, max consoles is 32
    203 [main] ssh 5198 cygwin_exception::open_stackdumpfile: Dumping stack trace to ssh.exe.stackdump
```
   but using `ssh.exe` in Bash is OK.

   `pslist64.exe -t` from [SysInternals](https://docs.microsoft.com/en-us/sysinternals) shows my system is indeed running 31 `ssh` processes.

```
  Code                         14208   8  31 6580 2173553932  102152   82604
    Code                        1780   8  16  378 2173196004   57516   95516
    Code                        2312   8  22  475 2188037608  160580  151364
    Code                        3364   8  24  457 2181660744  111120  114212
      Code                      8140   8  13  197 2173166512   16628   25464
      Code                     13788   8  45 2321 2173439292   98908  325436
        conhost                 1812   8   6  128 2151784964   10688    5400
        cmd                     3316   8   2  112 2151780392    8724    7528
          ssh                   1660   8   6  282 4840072   14296   10780
        cmd                     5572   8   2  112 2151780392   10208    7676
          ssh                  41452   8   6  282 4840072   14452   10800
        cmd                     6652   8   2  112 2151780392    8732    7524
          ssh                  37808   8   6  282 4840072   14652   10700
        cmd                     7340   8   2  112 2151780392    8824    7540
          ssh                  36480   8   6  282 4840072   14232   10784
        conhost                 8564   8   6  128 2151784964   10748    5460
        conhost                11952   8   6  128 2151784964   10752    5392
        conhost                13840   8   6  128 2151784964   11476    5508
        conhost                14424   8   6  128 2151784964   10756    5476
        cmd                    14904   8   2  112 2151780392   10136    7536
          ssh                  21148   8   6  282 4840072   14564   10780
        conhost                16164   8   6  128 2151784964   12132    5404
        cmd                    18756   8   2  112 2151780392    9452    7536
          ssh                  22624   8   6  282 4840072   15240   10724
        cmd                    18948   8   2  112 2151780392    9684    7632
          ssh                  16264   8   6  282 4840072   16160   10772
        cmd                    20872   8   2  112 2151780392    8728    7528
          ssh                   9308   8   6  282 4840072   14364   10796
        cmd                    23176   8   2  112 2151780392    8788    7632
          ssh                  43364   8   6  486 4840072   16072   12400
        cmd                    25196   8   2  112 2151780392    8848    7408
          ssh                  44464   8   6  282 4840072   14804   10720
        conhost                25820   8   6  128 2151784964   11008    5440
        conhost                27180   8   6  128 2151784964   12376    5392
        conhost                27216   8   6  128 2151784964   11504    5488
        cmd                    28204   8   2  112 2151780392   10376    7572
          ssh                  42784   8   6  282 4840072   15004   10792
        conhost                29608   8   6  128 2151784964   10688    5512
        cmd                    31340   8   2  112 2151780392   10168    7528
          ssh                  25128   8   6  282 4840072   14460   10816
        conhost                31448   8   6  128 2151784964   10712    5444
        conhost                31960   8   6  128 2151784964   11384    5484
        cmd                    32132   8   2  112 2151780392    9152    7656
          ssh                  44428   8   6  282 4840072   14680   10768
        conhost                32352   8   6  128 2151784964   10912    5436
        conhost                33540   8   6  128 2151784964   10840    5500
        conhost                33932   8   6  128 2151784964   10744    5380
        cmd                    34144   8   2  112 2151780392    8900    7524
          ssh                  21872   8   6  282 4840072   14480   10788
        cmd                    34152   8   2  112 2151780392    8804    7628
          ssh                  27740   8   6  282 4840072   14668   10784
        conhost                34424   8   6  128 2151784964   10800    5412
        cmd                    36124   8   2  112 2151780392    9252    7656
          ssh                  41036   8   6  282 4840072   15736   10780
        conhost                36184   8   6  128 2151784964   10760    5472
        cmd                    37340   8   2  112 2151780392    8636    7560
          ssh                  36228   8   6  282 4840072   14340   10720
        cmd                    37436   8   2  112 2151780392   10516    7636
          ssh                  18784   8   6  282 4840072   14392   10724
        conhost                37708   8   6  128 2151784964   10692    5420
        conhost                37824   8   6  128 2151784964   10996    5388
        conhost                37884   8   6  128 2151784964   10708    5512
        conhost                39124   8   6  128 2151784964   11064    5504
        cmd                    39812   8   2  112 2151780392    9424    7532
          ssh                  30768   8   6  282 4840072   14888   10780
        cmd                    39848   8   2  112 2151780392    9008    7412
          ssh                  41924   8   6  282 4840072   14680   10672
        conhost                39976   8   6  128 2151784964   11092    5496
        conhost                40200   8   6  128 2151784964   11056    5388
        conhost                40364   8   6  128 2151784964   10812    5484
        cmd                    41092   8   2  112 2151780392    9196    7532
          ssh                  37956   8   6  282 4840072   14372   10784
        cmd                    41188   8   2  112 2151780392    9604    7676
          ssh                  40036   8   6  282 4840072   14648   10772
        cmd                    41344   8   2  112 2151780392    8908    7632
          ssh                   9132   8   6  282 4840072   14348   10776
        conhost                41616   8   6  128 2151784964   10880    5460
        conhost                42816   8   6  128 2151784964   10920    5476
        cmd                    42876   8   2  112 2151780392    9712    7580
          ssh                  29816   8   6  282 4840072   15276   10800
        conhost                43196   8   6  128 2151784964   12408    5440
        conhost                43264   8   6  128 2151784964   11840    5380
        cmd                    43292   8   2  112 2151780392    8828    7540
          ssh                  38532   8   6  282 4840072   14656   10716
        conhost                43320   8   6  128 2151784964   11044    5452
        cmd                    43444   8   2  112 2151780392   10652    7532
          ssh                  43904   8   6  282 4840072   14896   10796
        conhost                43908   8   6  128 2151784964   11024    5488
        cmd                    44204   8   2  112 2151780392    8808    7656
          ssh                  31972   8   6  282 4840072   14748   10796
        conhost                44248   8   6  128 2151784964   11096    5504
        cmd                    44572   8   2  112 2151780392    8844    7544
          ssh                  35220   8   6  282 4840072   15060   10776
        cmd                    44932   8   2  112 2151780392    9628    7536
          ssh                  34920   8   6  282 4840072   16276   10800
        cmd                    44972   8   2  112 2151780392   10224    7532
          ssh                  35524   8   6  282 4840072   15340   10704
        cmd                    45004   8   2  112 2151780392   10416    7536
          ssh                  42492   8   6  282 4840072   15744   10800
      Code                     22688   8  13  197 2173166512   17140   25476
      Code                     33892   8  13  197 2173166512   37236   25580
      Code                     34888   8  13  197 2173166512   38176   25124
      Code                     44532   8  13  197 2173166512   39164   25588
      Code                     45340   8  13  197 2173166512   88744   24748
    Code                       10312   4  21  539 2188068736  183888  228592
    Code                       11340   8  16  428 2173196004   81424   92584
    Code                       12704   4  21  546 2188042724  224084  213628
    Code                       15844   8   8  337 2168791264    9896   14816
    Code                       15852   8  22  475 2188067776  262008  287272
    Code                       17340  10  20 1212 2170236996  384732  521080
    Code                       18256   4  20  539 2188026340  406784  512880
    Code                       22380   8  10  333 2168828424   24776   21520
    Code                       22448   8  21  551 2188039332  258936  261960
    Code                       38672   8  15  345 2173186788  119764   54328
    Code                       39216   8  15  378 2173187812   79400   68200
    Code                       44928   8  16  411 2173196004   71876   89176
    Code                       45000   8  16  413 2173196004   77992   67740
```

Question: I am not sure why vscode is running so many `ssh` processes, but can we increase this `max consoles` number from 32 to a bigger value, like 1024?
Thanks!

![image](https://user-images.githubusercontent.com/89552663/203181208-2f8a4b05-8bbb-4d18-bf73-83b70cbab7d4.png)

**Comment by yunwu-jnpr** [comment]
Thanks, @dscho . I will try and if I found anything useful I will update here. Thank you!

**Comment by yunwu-jnpr** [comment]
I realized it is not `ssh.exe` problem but Windows `cmd.exe` problem, because the problem can be reproduced by 
```
@for /L %i in (1,1,40) do ( start cmd /k D:\tool\git\usr\bin\ssh.exe <ssh-svr> )
```
but not 
```
@for /L %i in (1,1,40) do ( start        D:\tool\git\usr\bin\ssh.exe <ssh-svr> )
```

I have filed https://github.com/microsoft/vscode/issues/167096 for vscode community and hope they can fix it by launching `ssh.exe` without `cmd.exe`.
